name: CI and CD
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
  cd:
    name: Deploy with Cloudflare Pages
    runs-on: ubuntu-latest
    needs:
      - ci
    permissions:
      deployments: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: assets
          path: assets
      - name: Deploy with Cloudflare Pages
        id: cf
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: fff06038a70892193e0fa1e9e270436a
          projectName: my-home
          directory: assets
          branch: ${{ needs.branch-name.outputs.branch-name }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: 3
