name: CI and CD
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  ci-and-cd:
    name: Deploy with Cloudflare Pages
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install dev deps
        uses: jdx/mise-action@v3
      - name: Get pnpm cache directory path
        id: pnpm-cache-dir-path
        run: echo "dir=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v5
        with:
          path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key: pnpm-cache-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-cache-${{ runner.os }}-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Generate CSS
        run: |
          pnpm css
          rm -rf src/css/main.css
      - name: Format
        run: pnpm fmt
      - name: Deploy with Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: fff06038a70892193e0fa1e9e270436a
          command: pages deploy src --project-name=my-home --commit-dirty --branch ${{ github.head_ref || github.ref_name }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
