name: CI
on:
  workflow_call:
jobs:
  ci:
    name: Format and Prepare for deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install dev deps
        uses: jdx/mise-action@v3
      - name: Get pnpm cache directory path
        id: pnpm-cache-dir-path
        run: echo "dir=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v5
        with:
          path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key: pnpm-cache-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-cache-${{ runner.os }}-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Generate CSS
        run: |
          pnpm css
          rm -rf src/css/main.css
      - name: Format
        run: pnpm fmt
      - name: Upload files
        uses: actions/upload-artifact@v6
        with:
          name: assets
          path: src
