name: CI
on:
  workflow_call:
jobs:
  ci:
    name: Format and Prepare for deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Get node version from Volta
        id: get-node-version
        uses: keita-hino/get-node-version-from-volta@main
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ steps.get-node-version.outputs.nodeVersion }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm i
        shell: bash
      - name: Generate CSS
        run: |
          pnpm css
          rm -rf src/css/main.css
      - name: Format
        run: pnpm fmt
      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: src
